# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DeleteFiles@1
  displayName: 'Delete files from Build'
  inputs:
    SourceFolder: Build
    Contents: '**/*.csproj
    **/*.sln'

- task: DeleteFiles@1
  displayName: 'Delete files from Docs'
  inputs:
    SourceFolder: Docs
    Contents: '**/*.*'

- task: DeleteFiles@1
  displayName: 'Delete files from Quick-Starts'
  inputs:
    SourceFolder: Quick-Starts
    Contents: '**/*Framework-for-All.sln
    **/*Framework-for-Universal.sln
    **/*Framework-for-WPF.sln
    **/*Framework.UniversalApp.Core.csproj'

- task: DeleteFiles@1
  displayName: 'Delete files from Src'
  inputs:
    SourceFolder: Src
    Contents: '**/*.*'

- task: DeleteFiles@1
  displayName: 'Delete files from Vsix'
  inputs:
    SourceFolder: Vsix
    Contents: '**/*.*'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:OutDir=$(Build.ArtifactStagingDirectory)"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'