# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: DeleteFiles@1
  displayName: 'Delete files from Build'
  inputs:
    SourceFolder: Build
    Contents: '**/*.csproj'

- task: DeleteFiles@1
  displayName: 'Delete files from Docs'
  inputs:
    SourceFolder: Docs
    Contents: '**/*.shfbproj'

- task: DeleteFiles@1
  displayName: 'Delete files from Vsix'
  inputs:
    SourceFolder: Vsix
    Contents: '**/*.csproj'

- task: DeleteFiles@1
  displayName: 'Delete files from Src'
  inputs:
    SourceFolder: Src
    Contents: '**/GoodToCode.Framework.Universal.csproj'

- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'
